export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const SET_DOCTOR_START = "SET_DOCTOR_START";
export const SET_DOCTOR_SUCCESS = "SET_DOCTOR_SUCCESS";
export const SET_DOCTOR_FAIL = "SET_DOCTOR_FAIL";
export const SET_DOCTOR_DETAIL_START = "SET_DOCTOR_DETAIL_START";
export const SET_DOCTOR_DETAIL_SUCCESS = "SET_DOCTOR_DETAIL_SUCCESS";
export const SET_DOCTOR_DETAIL_FAIL = "SET_DOCTOR_DETAIL_FAIL";
export const SET_LOADING_DOCTOR = "SET_LOADING_DOCTOR";
export const SET_LOADING_DONE_DOCTOR = "SET_LOADING_DONE_DOCTOR";

export const SET_BOOKING_START = "SET_BOOKING_START";
export const SET_BOOKING_SUCCESS = "SET_BOOKING_SUCCESS";
export const SET_BOOKING_FAIL = "SET_BOOKING_FAIL";
export const SET_BOOKING_DETAIL_START = "SET_BOOKING_DETAIL_START";
export const SET_BOOKING_DETAIL_SUCCESS = "SET_BOOKING_DETAIL_SUCCESS";
export const SET_BOOKING_DETAIL_FAIL = "SET_BOOKING_DETAIL_FAIL";
export const SET_LOADING_BOOKING = "SET_LOADING_BOOKING";
export const SET_LOADING_DONE_BOOKING = "SET_LOADING_DONE_BOOKING";